version: '3.3'

services:
  api:
    build: .
    depends_on:
      - db
    environment:
      STAGE: run
      DATABASE_URL: postgres://fantasy:fantasy@db/leaderboard
      LEADERBOARD_DB: postgres://fantasy:fantasy@db/leaderboard
      LEADERBOARD_PORT: 3002
    networks:
      - default
    ports:
      - 3002:3002
    restart: always
    working_dir: /home/rust/leaderboard
    command: /bin/bash -c "./diesel setup && ./diesel migration run && ./leaderboard_server"

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_USER: fantasy
      POSTGRES_PASSWORD: fantasy
      POSTGRES_DB: leaderboard
    #image: postgres:latest
    networks:
      - default
    ports:
      - 3102:5432
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:

# https://github.com/ghotiphud/rust-web-starter/blob/master/docker-compose.yml