version: '3.3'

services:
  api:
    build: .
    depends_on:
      - db
    environment:
      STAGE: run
      DATABASE_URL: postgres://fantasy:fantasy@db/fantasy
      FANTASY_DB: postgres://fantasy:fantasy@db/fantasy
      FANTASY_PORT: 3003
      RESULT_PORT: 3001
      RESULT_ADDR: result_api
    networks:
      - default
    ports:
      - 3003:3003
    restart: always
    working_dir: /home/rust/fantasy
    command: /bin/bash -c "./diesel setup && ./diesel migration run && ./fantasy_server"

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_USER: fantasy
      POSTGRES_PASSWORD: fantasy
      POSTGRES_DB: fantasy
    #image: postgres:latest
    networks:
      - default
    ports:
      - 3103:5432
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      #- ./scripts:/docker-entrypoint-initdb.d
volumes:
  pg_data:

# https://github.com/ghotiphud/rust-web-starter/blob/master/docker-compose.yml